const char* spearman_cl = 
"\n"
"\n"
"\n"
"void switch_f(__local float* a, __local float* b)\n"
"{\n"
"   float c = *a;\n"
"   *a = *b;\n"
"   *b = c;\n"
"}\n"
"\n"
"\n"
"\n"
"void switch_i(__local int* a, __local int* b)\n"
"{\n"
"   int c = *a;\n"
"   *a = *b;\n"
"   *b = c;\n"
"}\n"
"\n"
"\n"
"\n"
"void build_lists(int aInd, int bInd, int size, int chunk, __local float* alist,\n"
"                 __local float* blist, __global float* exprs, __local int* rank)\n"
"{\n"
"   int i,ix;\n"
"   for (i=0;i<chunk;++i)\n"
"   {\n"
"      ix = (get_local_id(0)*chunk+i)*2;\n"
"      if (ix<size)\n"
"      {\n"
"         alist[ix] = exprs[ix+aInd];\n"
"         blist[ix] = exprs[ix+bInd];\n"
"         rank[ix] = ix+1;\n"
"      }\n"
"      else\n"
"      {\n"
"         alist[ix] = INFINITY;\n"
"         blist[ix] = INFINITY;\n"
"         rank[ix] = 0;\n"
"      }\n"
"      if ((ix+1)<size)\n"
"      {\n"
"         alist[ix+1] = exprs[ix+aInd+1];\n"
"         blist[ix+1] = exprs[ix+bInd+1];\n"
"         rank[ix+1] = ix+2;\n"
"      }\n"
"      else\n"
"      {\n"
"         alist[ix+1] = INFINITY;\n"
"         blist[ix+1] = INFINITY;\n"
"         rank[ix+1] = 0;\n"
"      }\n"
"   }\n"
"   barrier(CLK_LOCAL_MEM_FENCE);\n"
"}\n"
"\n"
"\n"
"\n"
"void bitonic_sort_ff(int chunk, __local float* sort, __local float* extra)\n"
"{\n"
"   int bsize = get_local_size(0)*2*chunk;\n"
"   int ob,ib,i,ix,dir,a,b,t;\n"
"   for (ob=2;ob<=bsize;ob*=2)\n"
"   {\n"
"      for (ib=ob;ib>=2;ib/=2)\n"
"      {\n"
"         for (i=0;i<chunk;++i)\n"
"         {\n"
"            ix = get_local_id(0)*chunk+i;\n"
"            dir = -((ix/(ob/2))&0x1);\n"
"            t = ib/2;\n"
"            a = (ix/t)*ib+(ix%t);\n"
"            b = a + t;\n"
"            if (((sort[a]>sort[b])&&!dir)||((sort[a]<sort[b])&&dir))\n"
"            {\n"
"               switch_f(&sort[a],&sort[b]);\n"
"               switch_f(&extra[a],&extra[b]);\n"
"            }\n"
"         }\n"
"         barrier(CLK_LOCAL_MEM_FENCE);\n"
"      }\n"
"   }\n"
"}\n"
"\n"
"\n"
"\n"
"void bitonic_sort_fi(int chunk, __local float* sort, __local int* extra)\n"
"{\n"
"   int bsize = get_local_size(0)*2*chunk;\n"
"   int ob,ib,i,ix,dir,a,b,t;\n"
"   for (ob=2;ob<=bsize;ob*=2)\n"
"   {\n"
"      for (ib=ob;ib>=2;ib/=2)\n"
"      {\n"
"         for (i=0;i<chunk;++i)\n"
"         {\n"
"            ix = get_local_id(0)*chunk+i;\n"
"            dir = -((ix/(ob/2))&0x1);\n"
"            t = ib/2;\n"
"            a = (ix/t)*ib+(ix%t);\n"
"            b = a + t;\n"
"            if (((sort[a]>sort[b])&&!dir)||((sort[a]<sort[b])&&dir))\n"
"            {\n"
"               switch_f(&sort[a],&sort[b]);\n"
"               switch_i(&extra[a],&extra[b]);\n"
"            }\n"
"         }\n"
"         barrier(CLK_LOCAL_MEM_FENCE);\n"
"      }\n"
"   }\n"
"}\n"
"\n"
"\n"
"\n"
"long calc_ranks(int size, int chunk, __local long* sums, __local int* ranks)\n"
"{\n"
"   long c;\n"
"   int i,ix;\n"
"   for (i=0;i<chunk;++i)\n"
"   {\n"
"      ix = (get_local_id(0)*chunk+i)*2;\n"
"      if (ix<size)\n"
"      {\n"
"         c = ranks[ix]-(ix+1);\n"
"         sums[ix] = c*c;\n"
"      }\n"
"      else\n"
"      {\n"
"         sums[ix] = 0.0;\n"
"      }\n"
"      if ((ix+1)<size)\n"
"      {\n"
"         c = ranks[ix+1]-(ix+2);\n"
"         sums[ix+1] = c*c;\n"
"      }\n"
"      else\n"
"      {\n"
"         sums[ix+1] = 0.0;\n"
"      }\n"
"   }\n"
"   barrier(CLK_LOCAL_MEM_FENCE);\n"
"}\n"
"\n"
"\n"
"\n"
"void accumulate(int chunk, __local long* summation)\n"
"{\n"
"   int hbsize = get_local_size(0)*chunk;\n"
"   int i,ix,b;\n"
"   for (b=hbsize;b>=1;b/=2)\n"
"   {\n"
"      for (i=0;i<chunk;++i)\n"
"      {\n"
"         ix = get_local_id(0)*chunk+i;\n"
"         if (ix<b)\n"
"         {\n"
"            summation[ix] += summation[ix+b];\n"
"         }\n"
"      }\n"
"      barrier(CLK_LOCAL_MEM_FENCE);\n"
"   }\n"
"}\n"
"\n"
"\n"
"\n"
"__kernel void spearman(int size, int chunk, __global int* insts, __global float* exprs,\n"
"                       __global float* result, __local float* alist, __local float* blist,\n"
"                       __local int* rank, __local long* summation)\n"
"{\n"
"   int i = get_group_id(0)*2;\n"
"   build_lists(insts[i],insts[i+1],size,chunk,alist,blist,exprs,rank);\n"
"   bitonic_sort_ff(chunk,alist,blist);\n"
"   bitonic_sort_fi(chunk,blist,rank);\n"
"   calc_ranks(size,chunk,summation,rank);\n"
"   accumulate(chunk,summation);\n"
"   if (get_local_id(0)==0)\n"
"   {\n"
"      *result = 1.0-(6.0*summation[0]/((float)(size*(size*size-1))));\n"
"   }\n"
"}\n"
"";
